package com.vodafone.er.ecom.proxy.gettransactions;

import com.vizzavi.ecommerce.business.charging.PurchaseAttributes;
import com.vizzavi.ecommerce.business.charging.PurchaseAuthorization;
import com.vizzavi.ecommerce.business.charging.UsageAttributes;
import com.vizzavi.ecommerce.business.charging.UsageAuthorization;
import com.vizzavi.ecommerce.business.common.EcomApiFactory;
import com.vizzavi.ecommerce.business.common.EcommerceException;
import com.vizzavi.ecommerce.business.selfcare.Transaction;
import com.vizzavi.ecommerce.business.selfcare.TransactionFilter;
import com.vodafone.global.er.subscriptionmanagement.TransactionFilterImpl;
import org.assertj.core.api.SoftAssertions;
import org.junit.Ignore;

import java.util.Locale;
import java.util.Random;

import static org.junit.Assert.*;

/**
 * Created by Ravi Aghera
 */
public class GetTransaction17_IT_pt2 {

    private SoftAssertions softly = new SoftAssertions();

    @Ignore(value = "Ignored because this cannot be translated to Decoupling")
//    @Test
    public void getTransaction17() throws EcommerceException {
        final String msisdn = String.valueOf(new Random().nextInt());
        String packageId = "pAlt__X__package:pAlt_TAX_3_2_999_999_999_*_*";
        String serviceId = "sAlt";

        PurchaseAuthorization auth = EcomApiFactory.getPurchaseApi(Locale.UK).purchasePackageMsisdn("test", msisdn, packageId, new PurchaseAttributes());
        assertTrue(auth.isSuccess());
        final UsageAuthorization uAuth = EcomApiFactory.getChargingApi(Locale.UK).usageAuthRateCharge("test", msisdn, serviceId, new UsageAttributes());
        assertTrue(uAuth.isSuccess());

        TransactionFilter filter = new TransactionFilterImpl();
        filter.setTransactionIdLong(auth.getTransactionIdLong());
        Transaction transaction = EcomApiFactory.getSelfcareApi(Locale.UK)
                .getTransaction("test", filter);
        assertNotNull(transaction);

        System.out.println("PurchaseTrans: " + transaction.getType());

        assertEquals(auth.getTransactionIdLong(), transaction.getTransactionIdLong());


// java.util.HashMap
        softly.assertThat(transaction.getSubscription().getPackage().getPartnerInfo() ).as(" transaction.getSubscription().getPackage().getPartnerInfo()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPackage().getIsPackageModel() ).as(" transaction.getSubscription().getPackage().getIsPackageModel()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPackage().isParentPackage() ).as(" transaction.getSubscription().getPackage().isParentPackage()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPackage().getChildPackages() ).as(" transaction.getSubscription().getPackage().getChildPackages()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPackage().getServicesNotInPackageFairUsagePolicyList() ).as(" transaction.getSubscription().getPackage().getServicesNotInPackageFairUsagePolicyList()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPackage().isHasParentSub() ).as(" transaction.getSubscription().getPackage().isHasParentSub()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPackage().getParentSubId() ).as(" transaction.getSubscription().getPackage().getParentSubId()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPackage().isHasParentSubSuspendedResProv() ).as(" transaction.getSubscription().getPackage().isHasParentSubSuspendedResProv()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPackage().getParentSubStatus() ).as(" transaction.getSubscription().getPackage().getParentSubStatus()" ).isEqualTo(0) ;
        softly.assertThat(transaction.getSubscription().getPackage().isDisallowCancellations() ).as(" transaction.getSubscription().getPackage().isDisallowCancellations()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPackage().getSalesModel() ).as(" transaction.getSubscription().getPackage().getSalesModel()" ).isEqualTo("Reseller");
        softly.assertThat(transaction.getSubscription().getPackage().getPackageClass() ).as(" transaction.getSubscription().getPackage().getPackageClass()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPackage().isDataVoiceTariffInclusive() ).as(" transaction.getSubscription().getPackage().isDataVoiceTariffInclusive()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPackage().getNominalValue() ).as(" transaction.getSubscription().getPackage().getNominalValue()" ).isEqualTo(new Double(0.0)) ;
        softly.assertThat(transaction.getSubscription().getPackage().isUseBeingDeprovisionedStatus() ).as(" transaction.getSubscription().getPackage().isUseBeingDeprovisionedStatus()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPackage().getDisallowDuplicateSubPurchase() ).as(" transaction.getSubscription().getPackage().getDisallowDuplicateSubPurchase()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPackage().getNoActivePricepoints() ).as(" transaction.getSubscription().getPackage().getNoActivePricepoints()" ).isEqualTo(2) ;
        softly.assertThat(transaction.getSubscription().getPackage().isHasBalanceImpactsWithDate() ).as(" transaction.getSubscription().getPackage().isHasBalanceImpactsWithDate()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPackage().isHasPricePointsWithDate() ).as(" transaction.getSubscription().getPackage().isHasPricePointsWithDate()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPackage().isHasPromosWithDate() ).as(" transaction.getSubscription().getPackage().isHasPromosWithDate()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPackage().isHasTaxRateWithDate() ).as(" transaction.getSubscription().getPackage().isHasTaxRateWithDate()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPackage().getPromoCodeMap() ).as(" transaction.getSubscription().getPackage().getPromoCodeMap()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPackage().getPromoCodeMapSize() ).as(" transaction.getSubscription().getPackage().getPromoCodeMapSize()" ).isEqualTo(0) ;
        softly.assertThat(transaction.getSubscription().getPackage().getActiveStatusAsString() ).as(" transaction.getSubscription().getPackage().getActiveStatusAsString()" ).isEqualTo("ACTIVE");
        softly.assertThat(transaction.getSubscription().getPackage().isUseRateCardService() ).as(" transaction.getSubscription().getPackage().isUseRateCardService()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPackage().getRateCardServiceId() ).as(" transaction.getSubscription().getPackage().getRateCardServiceId()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPackage().isUserGroupCalendarPricePointPackage() ).as(" transaction.getSubscription().getPackage().isUserGroupCalendarPricePointPackage()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPackage().isUpsellDiscountProrated() ).as(" transaction.getSubscription().getPackage().isUpsellDiscountProrated()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPackage().isDisallowPrerate() ).as(" transaction.getSubscription().getPackage().isDisallowPrerate()" ).isFalse() ;
//check size of array!
        softly.assertThat(transaction.getSubscription().getPackage().getServiceNames().length ).as(" transaction.getSubscription().getPackage().getServiceNames().length" ).isEqualTo(1) ;
        softly.assertThat(transaction.getSubscription().getPackage().getDefaultPartnerProvisioningId() ).as(" transaction.getSubscription().getPackage().getDefaultPartnerProvisioningId()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPackage().getUserGroupComparisonAtRenewal() ).as(" transaction.getSubscription().getPackage().getUserGroupComparisonAtRenewal()" ).isEqualTo("SYSTEM");
        softly.assertThat(transaction.getSubscription().getPackage().isDefault() ).as(" transaction.getSubscription().getPackage().isDefault()" ).isFalse() ;
// java.util.HashMap
        softly.assertThat(transaction.getSubscription().getPackage().getParentPackageId() ).as(" transaction.getSubscription().getPackage().getParentPackageId()" ).isNullOrEmpty();
        softly.assertThat(transaction.getSubscription().getCountry() ).as(" transaction.getSubscription().getCountry()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPartnerId() ).as(" transaction.getSubscription().getPartnerId()" ).isNull();
        softly.assertThat(transaction.getSubscription().getSubscriptionIdLong() ).as(" transaction.getSubscription().getSubscriptionIdLong()" ).isEqualTo(new Long(8542)) ;
// com.vizzavi.ecommerce.business.catalog.PricePoint
// com.vizzavi.ecommerce.business.common.ChargingResource
        softly.assertThat(transaction.getSubscription().getPricePoint().getResource().getName() ).as(" transaction.getSubscription().getPricePoint().getResource().getName()" ).isEqualTo("GBP");
        softly.assertThat(transaction.getSubscription().getPricePoint().getResource().isCurrency() ).as(" transaction.getSubscription().getPricePoint().getResource().isCurrency()" ).isTrue() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getResource().isResource() ).as(" transaction.getSubscription().getPricePoint().getResource().isResource()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getResource().isToken() ).as(" transaction.getSubscription().getPricePoint().getResource().isToken()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getResource().isUsageToken() ).as(" transaction.getSubscription().getPricePoint().getResource().isUsageToken()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getResource().isPayToken() ).as(" transaction.getSubscription().getPricePoint().getResource().isPayToken()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getResource().getResourceSymbol() ).as(" transaction.getSubscription().getPricePoint().getResource().getResourceSymbol()" ).isEqualTo("ChargingResource_Symbol_826");
        softly.assertThat(transaction.getSubscription().getPricePoint().getResource().getCode() ).as(" transaction.getSubscription().getPricePoint().getResource().getCode()" ).isEqualTo(826) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getResource().getDescription() ).as(" transaction.getSubscription().getPricePoint().getResource().getDescription()" ).isEqualTo("British Pound Sterling");
        softly.assertThat(transaction.getSubscription().getPricePoint().getResource().getResourceName() ).as(" transaction.getSubscription().getPricePoint().getResource().getResourceName()" ).isEqualTo("ChargingResource_826");
        softly.assertThat(transaction.getSubscription().getPricePoint().getResource().getCountryId() ).as(" transaction.getSubscription().getPricePoint().getResource().getCountryId()" ).isEqualTo(0) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getKey() ).as(" transaction.getSubscription().getPricePoint().getKey()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getId() ).as(" transaction.getSubscription().getPricePoint().getId()" ).isEqualTo("package:pAlt_TAX_3_2_999_999_999_*_*");
        softly.assertThat(transaction.getSubscription().getPricePoint().isZeroCostIgnore() ).as(" transaction.getSubscription().getPricePoint().isZeroCostIgnore()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getStartDate() ).as(" transaction.getSubscription().getPricePoint().getStartDate()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().isActive() ).as(" transaction.getSubscription().getPricePoint().isActive()" ).isTrue() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().isPreOrder() ).as(" transaction.getSubscription().getPricePoint().isPreOrder()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getTaxRate() ).as(" transaction.getSubscription().getPricePoint().getTaxRate()" ).isEqualTo(new Double(0.175)) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getTaxCode() ).as(" transaction.getSubscription().getPricePoint().getTaxCode()" ).isEqualTo("TAX");
        softly.assertThat(transaction.getSubscription().getPricePoint().getLinkedByTrialPricepoint() ).as(" transaction.getSubscription().getPricePoint().getLinkedByTrialPricepoint()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getExpiryDate() ).as(" transaction.getSubscription().getPricePoint().getExpiryDate()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getResourceBalances() ).as(" transaction.getSubscription().getPricePoint().getResourceBalances()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().isDiscount() ).as(" transaction.getSubscription().getPricePoint().isDiscount()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getDiscountPromoText() ).as(" transaction.getSubscription().getPricePoint().getDiscountPromoText()" ).isNullOrEmpty();
        softly.assertThat(transaction.getSubscription().getPricePoint().getPackageId() ).as(" transaction.getSubscription().getPricePoint().getPackageId()" ).isEqualTo("pAlt");
        softly.assertThat(transaction.getSubscription().getPricePoint().getContentId() ).as(" transaction.getSubscription().getPricePoint().getContentId()" ).isEqualTo("*");
        softly.assertThat(transaction.getSubscription().getPricePoint().getPricingText1() ).as(" transaction.getSubscription().getPricePoint().getPricingText1()" ).isNullOrEmpty();
        softly.assertThat(transaction.getSubscription().getPricePoint().getPricingText2() ).as(" transaction.getSubscription().getPricePoint().getPricingText2()" ).isNullOrEmpty();
        softly.assertThat(transaction.getSubscription().getPricePoint().getUsageTime() ).as(" transaction.getSubscription().getPricePoint().getUsageTime()" ).isEqualTo(new Long(0)) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getAccessDuration() ).as(" transaction.getSubscription().getPricePoint().getAccessDuration()" ).isEqualTo(new Double(0.0)) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getCustomResourceBalances() ).as(" transaction.getSubscription().getPricePoint().getCustomResourceBalances()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getPricingModelTier() ).as(" transaction.getSubscription().getPricePoint().getPricingModelTier()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().isArchived() ).as(" transaction.getSubscription().getPricePoint().isArchived()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().isBasePricePoint() ).as(" transaction.getSubscription().getPricePoint().isBasePricePoint()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getAccessDevice() ).as(" transaction.getSubscription().getPricePoint().getAccessDevice()" ).isEqualTo(999) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getAlternativeRate() ).as(" transaction.getSubscription().getPricePoint().getAlternativeRate()" ).isEqualTo(new Double(11.75)) ;
//check size of array!
        softly.assertThat(transaction.getSubscription().getPricePoint().getBalanceImpacts().length ).as(" transaction.getSubscription().getPricePoint().getBalanceImpacts().length" ).isEqualTo(0) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().isTrial() ).as(" transaction.getSubscription().getPricePoint().isTrial()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getGlid() ).as(" transaction.getSubscription().getPricePoint().getGlid()" ).isNullOrEmpty();
// java.util.HashMap
        softly.assertThat(transaction.getSubscription().getPricePoint().getPricepointIdLink() ).as(" transaction.getSubscription().getPricePoint().getPricepointIdLink()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().isPreview() ).as(" transaction.getSubscription().getPricePoint().isPreview()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getInteractiveFlag() ).as(" transaction.getSubscription().getPricePoint().getInteractiveFlag()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().isForcedPurchase() ).as(" transaction.getSubscription().getPricePoint().isForcedPurchase()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().isSubscriptionDuplicate() ).as(" transaction.getSubscription().getPricePoint().isSubscriptionDuplicate()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getFixedExpiryDate() ).as(" transaction.getSubscription().getPricePoint().getFixedExpiryDate()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().isReserveOnly() ).as(" transaction.getSubscription().getPricePoint().isReserveOnly()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getMinSubPeriod() ).as(" transaction.getSubscription().getPricePoint().getMinSubPeriod()" ).isEqualTo(0) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getPenaltyCharges() ).as(" transaction.getSubscription().getPricePoint().getPenaltyCharges()" ).isEqualTo(new Double(0.0)) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getCancellation() ).as(" transaction.getSubscription().getPricePoint().getCancellation()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getMonthEndSubscription() ).as(" transaction.getSubscription().getPricePoint().getMonthEndSubscription()" ).isEqualTo("NULL");
        softly.assertThat(transaction.getSubscription().getPricePoint().isHistoric() ).as(" transaction.getSubscription().getPricePoint().isHistoric()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getFixedRecurrence() ).as(" transaction.getSubscription().getPricePoint().getFixedRecurrence()" ).isEqualTo(new Long(0)) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().isFixedRecurringPricePoint() ).as(" transaction.getSubscription().getPricePoint().isFixedRecurringPricePoint()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().isReceipting() ).as(" transaction.getSubscription().getPricePoint().isReceipting()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getReceiptingAttribute() ).as(" transaction.getSubscription().getPricePoint().getReceiptingAttribute()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getOrder() ).as(" transaction.getSubscription().getPricePoint().getOrder()" ).isEqualTo(0) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getPaymentHandler() ).as(" transaction.getSubscription().getPricePoint().getPaymentHandler()" ).isEqualTo("NULL");
//check size of array!
        softly.assertThat(transaction.getSubscription().getPricePoint().getNonMatchAllUserGroups().length ).as(" transaction.getSubscription().getPricePoint().getNonMatchAllUserGroups().length" ).isEqualTo(0) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().isPromo() ).as(" transaction.getSubscription().getPricePoint().isPromo()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().isSubmitToPaymentHandler() ).as(" transaction.getSubscription().getPricePoint().isSubmitToPaymentHandler()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().isSuppressToPaymentHandler() ).as(" transaction.getSubscription().getPricePoint().isSuppressToPaymentHandler()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getPricingTextTemplateName1() ).as(" transaction.getSubscription().getPricePoint().getPricingTextTemplateName1()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getPricingTextTemplateName2() ).as(" transaction.getSubscription().getPricePoint().getPricingTextTemplateName2()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getTranslatedPricingText1() ).as(" transaction.getSubscription().getPricePoint().getTranslatedPricingText1()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getTranslatedPricingText2() ).as(" transaction.getSubscription().getPricePoint().getTranslatedPricingText2()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getRecurrenceDay() ).as(" transaction.getSubscription().getPricePoint().getRecurrenceDay()" ).isEqualTo(-1) ;
// java.util.HashMap
// java.util.HashMap
        softly.assertThat(transaction.getSubscription().getPricePoint().isAlignWithExternal() ).as(" transaction.getSubscription().getPricePoint().isAlignWithExternal()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getGracePeriod() ).as(" transaction.getSubscription().getPricePoint().getGracePeriod()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getRetryFrequency() ).as(" transaction.getSubscription().getPricePoint().getRetryFrequency()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getSuspensionPeriod() ).as(" transaction.getSubscription().getPricePoint().getSuspensionPeriod()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().isGraceSuspensionRetryFrequencyUndefined() ).as(" transaction.getSubscription().getPricePoint().isGraceSuspensionRetryFrequencyUndefined()" ).isTrue() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getTranslatedPricingText() ).as(" transaction.getSubscription().getPricePoint().getTranslatedPricingText()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getFairUsageLimit() ).as(" transaction.getSubscription().getPricePoint().getFairUsageLimit()" ).isEqualTo(-1) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getFairUsagePeriod() ).as(" transaction.getSubscription().getPricePoint().getFairUsagePeriod()" ).isEqualTo(-1) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getFairUsagePeriodUnit() ).as(" transaction.getSubscription().getPricePoint().getFairUsagePeriodUnit()" ).isEqualTo("Day(s)");
        softly.assertThat(transaction.getSubscription().getPricePoint().getExtensionPeriod() ).as(" transaction.getSubscription().getPricePoint().getExtensionPeriod()" ).isEqualTo(0) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().isIncludeServiceForPackageFUP() ).as(" transaction.getSubscription().getPricePoint().isIncludeServiceForPackageFUP()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().isFairUsagePolicyEnabled() ).as(" transaction.getSubscription().getPricePoint().isFairUsagePolicyEnabled()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().isTariff() ).as(" transaction.getSubscription().getPricePoint().isTariff()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().isHideForPurchaseOptions() ).as(" transaction.getSubscription().getPricePoint().isHideForPurchaseOptions()" ).isFalse() ;
// com.vizzavi.ecommerce.business.catalog.Tax
        softly.assertThat(transaction.getSubscription().getPricePoint().getTax().getName() ).as(" transaction.getSubscription().getPricePoint().getTax().getName()" ).isEqualTo("TAX");
        softly.assertThat(transaction.getSubscription().getPricePoint().getTax().getKey() ).as(" transaction.getSubscription().getPricePoint().getTax().getKey()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getTax().getTaxRate() ).as(" transaction.getSubscription().getPricePoint().getTax().getTaxRate()" ).isEqualTo(new Double(0.175)) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getTax().getTaxCode() ).as(" transaction.getSubscription().getPricePoint().getTax().getTaxCode()" ).isEqualTo("TAX");
        softly.assertThat(transaction.getSubscription().getPricePoint().getBalances() ).as(" transaction.getSubscription().getPricePoint().getBalances()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().isRecurring() ).as(" transaction.getSubscription().getPricePoint().isRecurring()" ).isTrue() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getRenewalsUntilLinkedPricepoint() ).as(" transaction.getSubscription().getPricePoint().getRenewalsUntilLinkedPricepoint()" ).isEqualTo(-1) ;
// com.vizzavi.ecommerce.business.catalog.internal.PricePointTier
        softly.assertThat(transaction.getSubscription().getPricePoint().getPricePointTier().getKey() ).as(" transaction.getSubscription().getPricePoint().getPricePointTier().getKey()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getPricePointTier().getPromotionalPrice() ).as(" transaction.getSubscription().getPricePoint().getPricePointTier().getPromotionalPrice()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getPricePointTier().getPromotionalPricingText() ).as(" transaction.getSubscription().getPricePoint().getPricePointTier().getPromotionalPricingText()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getPricePointTier().getPricingModel() ).as(" transaction.getSubscription().getPricePoint().getPricePointTier().getPricingModel()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getPricePointTier().getTier() ).as(" transaction.getSubscription().getPricePoint().getPricePointTier().getTier()" ).isEqualTo("default");
        softly.assertThat(transaction.getSubscription().getPricePoint().getPricePointTier().isDefaultPPT() ).as(" transaction.getSubscription().getPricePoint().getPricePointTier().isDefaultPPT()" ).isTrue() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getPricePointTier().getPromotionalPricingTextList() ).as(" transaction.getSubscription().getPricePoint().getPricePointTier().getPromotionalPricingTextList()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getPackageIdentifier() ).as(" transaction.getSubscription().getPricePoint().getPackageIdentifier()" ).isEqualTo("package:pAlt_TAX_3_2_999_999_999_*_*_*_false_false_*");
        softly.assertThat(transaction.getSubscription().getPricePoint().getServiceIdentifier() ).as(" transaction.getSubscription().getPricePoint().getServiceIdentifier()" ).isEqualTo("content:pAlt_TAX_*_999_999_*_999_999");
// com.vizzavi.ecommerce.business.common.ChargingResource
        softly.assertThat(transaction.getSubscription().getPricePoint().getResourceField().getName() ).as(" transaction.getSubscription().getPricePoint().getResourceField().getName()" ).isEqualTo("GBP");
        softly.assertThat(transaction.getSubscription().getPricePoint().getResourceField().isCurrency() ).as(" transaction.getSubscription().getPricePoint().getResourceField().isCurrency()" ).isTrue() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getResourceField().isResource() ).as(" transaction.getSubscription().getPricePoint().getResourceField().isResource()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getResourceField().isToken() ).as(" transaction.getSubscription().getPricePoint().getResourceField().isToken()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getResourceField().isUsageToken() ).as(" transaction.getSubscription().getPricePoint().getResourceField().isUsageToken()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getResourceField().isPayToken() ).as(" transaction.getSubscription().getPricePoint().getResourceField().isPayToken()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getResourceField().getResourceSymbol() ).as(" transaction.getSubscription().getPricePoint().getResourceField().getResourceSymbol()" ).isEqualTo("ChargingResource_Symbol_826");
        softly.assertThat(transaction.getSubscription().getPricePoint().getResourceField().getCode() ).as(" transaction.getSubscription().getPricePoint().getResourceField().getCode()" ).isEqualTo(826) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getResourceField().getDescription() ).as(" transaction.getSubscription().getPricePoint().getResourceField().getDescription()" ).isEqualTo("British Pound Sterling");
        softly.assertThat(transaction.getSubscription().getPricePoint().getResourceField().getResourceName() ).as(" transaction.getSubscription().getPricePoint().getResourceField().getResourceName()" ).isEqualTo("ChargingResource_826");
        softly.assertThat(transaction.getSubscription().getPricePoint().getResourceField().getCountryId() ).as(" transaction.getSubscription().getPricePoint().getResourceField().getCountryId()" ).isEqualTo(0) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getStandardRateWithoutTax() ).as(" transaction.getSubscription().getPricePoint().getStandardRateWithoutTax()" ).isEqualTo(new Double(10.0)) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().isVolumeType() ).as(" transaction.getSubscription().getPricePoint().isVolumeType()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().isOriginal() ).as(" transaction.getSubscription().getPricePoint().isOriginal()" ).isFalse() ;
//check size of array!
        softly.assertThat(transaction.getSubscription().getPricePoint().getPricePointTiers().length ).as(" transaction.getSubscription().getPricePoint().getPricePointTiers().length" ).isEqualTo(1) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getPricePointTiers()[0].getKey() ).as(" transaction.getSubscription().getPricePoint().getPricePointTiers()[0].getKey()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getPricePointTiers()[0].getPromotionalPrice() ).as(" transaction.getSubscription().getPricePoint().getPricePointTiers()[0].getPromotionalPrice()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getPricePointTiers()[0].getPromotionalPricingText() ).as(" transaction.getSubscription().getPricePoint().getPricePointTiers()[0].getPromotionalPricingText()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getPricePointTiers()[0].getPricingModel() ).as(" transaction.getSubscription().getPricePoint().getPricePointTiers()[0].getPricingModel()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getPricePointTiers()[0].getTier() ).as(" transaction.getSubscription().getPricePoint().getPricePointTiers()[0].getTier()" ).isEqualTo("default");
        softly.assertThat(transaction.getSubscription().getPricePoint().getPricePointTiers()[0].isDefaultPPT() ).as(" transaction.getSubscription().getPricePoint().getPricePointTiers()[0].isDefaultPPT()" ).isTrue() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getPricePointTiers()[0].getPromotionalPricingTextList() ).as(" transaction.getSubscription().getPricePoint().getPricePointTiers()[0].getPromotionalPricingTextList()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getProtectedFk() ).as(" transaction.getSubscription().getPricePoint().getProtectedFk()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getmPricingText1() ).as(" transaction.getSubscription().getPricePoint().getmPricingText1()" ).isNullOrEmpty();
        softly.assertThat(transaction.getSubscription().getPricePoint().getmPricingText2() ).as(" transaction.getSubscription().getPricePoint().getmPricingText2()" ).isNullOrEmpty();
        softly.assertThat(transaction.getSubscription().getPricePoint().isNonRecurring() ).as(" transaction.getSubscription().getPricePoint().isNonRecurring()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().isEvent() ).as(" transaction.getSubscription().getPricePoint().isEvent()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getDescription() ).as(" transaction.getSubscription().getPricePoint().getDescription()" ).isEqualTo("Recurring 7 day");
        softly.assertThat(transaction.getSubscription().getPricePoint().getRate() ).as(" transaction.getSubscription().getPricePoint().getRate()" ).isEqualTo(new Double(11.75)) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getStandardRate() ).as(" transaction.getSubscription().getPricePoint().getStandardRate()" ).isEqualTo(new Double(11.75)) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getNetRate() ).as(" transaction.getSubscription().getPricePoint().getNetRate()" ).isEqualTo(new Double(10.0)) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().isAlwaysValidateMsisdn() ).as(" transaction.getSubscription().getPricePoint().isAlwaysValidateMsisdn()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getChannel() ).as(" transaction.getSubscription().getPricePoint().getChannel()" ).isEqualTo(999) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getPartnerId() ).as(" transaction.getSubscription().getPricePoint().getPartnerId()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getMultiUsageMode() ).as(" transaction.getSubscription().getPricePoint().getMultiUsageMode()" ).isEqualTo(0) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getNetworkCodeMatchMethod() ).as(" transaction.getSubscription().getPricePoint().getNetworkCodeMatchMethod()" ).isEqualTo(0) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().isPreRatePriceGross() ).as(" transaction.getSubscription().getPricePoint().isPreRatePriceGross()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getPreRate() ).as(" transaction.getSubscription().getPricePoint().getPreRate()" ).isEqualTo(new Double(-1.0)) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getPaymentInformation() ).as(" transaction.getSubscription().getPricePoint().getPaymentInformation()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getContentName() ).as(" transaction.getSubscription().getPricePoint().getContentName()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getAssetID() ).as(" transaction.getSubscription().getPricePoint().getAssetID()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getPremiumLevel() ).as(" transaction.getSubscription().getPricePoint().getPremiumLevel()" ).isEqualTo(999) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getReserveOnlyFlag() ).as(" transaction.getSubscription().getPricePoint().getReserveOnlyFlag()" ).isEqualTo(0) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getSupplierId() ).as(" transaction.getSubscription().getPricePoint().getSupplierId()" ).isEqualTo("*");
        softly.assertThat(transaction.getSubscription().getPricePoint().getDeviceType() ).as(" transaction.getSubscription().getPricePoint().getDeviceType()" ).isEqualTo(999) ;
//check size of array!
        softly.assertThat(transaction.getSubscription().getPricePoint().getUserGroups().length ).as(" transaction.getSubscription().getPricePoint().getUserGroups().length" ).isEqualTo(1) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getUserGroup() ).as(" transaction.getSubscription().getPricePoint().getUserGroup()" ).isEqualTo("*");
        softly.assertThat(transaction.getSubscription().getPricePoint().getPaymentType() ).as(" transaction.getSubscription().getPricePoint().getPaymentType()" ).isEqualTo(999) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getEventDateTime() ).as(" transaction.getSubscription().getPricePoint().getEventDateTime()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getEventUnits() ).as(" transaction.getSubscription().getPricePoint().getEventUnits()" ).isEqualTo(new Double(0.0)) ;
//check size of array!
        softly.assertThat(transaction.getSubscription().getPricePoint().getPromoCodes().length ).as(" transaction.getSubscription().getPricePoint().getPromoCodes().length" ).isEqualTo(1) ;
//check size of array!
        softly.assertThat(transaction.getSubscription().getPricePoint().getBearerIds().length ).as(" transaction.getSubscription().getPricePoint().getBearerIds().length" ).isEqualTo(1) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getPromoCode() ).as(" transaction.getSubscription().getPricePoint().getPromoCode()" ).isEqualTo("*");
        softly.assertThat(transaction.getSubscription().getPricePoint().getDuration() ).as(" transaction.getSubscription().getPricePoint().getDuration()" ).isEqualTo(2) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getChargingMethod() ).as(" transaction.getSubscription().getPricePoint().getChargingMethod()" ).isEqualTo(3) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getBearer() ).as(" transaction.getSubscription().getPricePoint().getBearer()" ).isEqualTo("*");
        softly.assertThat(transaction.getSubscription().getPricePoint().isInteractive() ).as(" transaction.getSubscription().getPricePoint().isInteractive()" ).isTrue() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().isIncludeUnavailable() ).as(" transaction.getSubscription().getPricePoint().isIncludeUnavailable()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getExpressFlag() ).as(" transaction.getSubscription().getPricePoint().getExpressFlag()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().isExpressFlag() ).as(" transaction.getSubscription().getPricePoint().isExpressFlag()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().isCancellationUsage() ).as(" transaction.getSubscription().getPricePoint().isCancellationUsage()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getTierName() ).as(" transaction.getSubscription().getPricePoint().getTierName()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getPromoPrecode() ).as(" transaction.getSubscription().getPricePoint().getPromoPrecode()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getUniquePromoCode() ).as(" transaction.getSubscription().getPricePoint().getUniquePromoCode()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getPromoUniqueCode() ).as(" transaction.getSubscription().getPricePoint().getPromoUniqueCode()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getNextCycleDiscount() ).as(" transaction.getSubscription().getPricePoint().getNextCycleDiscount()" ).isEqualTo(new Double(0.0)) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getHasHistoricPricePointFlag() ).as(" transaction.getSubscription().getPricePoint().getHasHistoricPricePointFlag()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().isIsForRenewal() ).as(" transaction.getSubscription().getPricePoint().isIsForRenewal()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getTaxRateAsDouble() ).as(" transaction.getSubscription().getPricePoint().getTaxRateAsDouble()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getAffiliateID() ).as(" transaction.getSubscription().getPricePoint().getAffiliateID()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getTariff() ).as(" transaction.getSubscription().getPricePoint().getTariff()" ).isEqualTo("*");
        softly.assertThat(transaction.getSubscription().getPricePoint().getAggregatorId() ).as(" transaction.getSubscription().getPricePoint().getAggregatorId()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().isForcePurchaseFlow() ).as(" transaction.getSubscription().getPricePoint().isForcePurchaseFlow()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getReceipientMsisdn() ).as(" transaction.getSubscription().getPricePoint().getReceipientMsisdn()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getProductCode() ).as(" transaction.getSubscription().getPricePoint().getProductCode()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getMerchantName() ).as(" transaction.getSubscription().getPricePoint().getMerchantName()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getInvoiceText() ).as(" transaction.getSubscription().getPricePoint().getInvoiceText()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().isReIssueEnabled() ).as(" transaction.getSubscription().getPricePoint().isReIssueEnabled()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().isReIssueFlagPresent() ).as(" transaction.getSubscription().getPricePoint().isReIssueFlagPresent()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getShortPackageId() ).as(" transaction.getSubscription().getPricePoint().getShortPackageId()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getHistoryStartDate() ).as(" transaction.getSubscription().getPricePoint().getHistoryStartDate()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getVendorId() ).as(" transaction.getSubscription().getPricePoint().getVendorId()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().isIsForNextPaymentAmount() ).as(" transaction.getSubscription().getPricePoint().isIsForNextPaymentAmount()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getRenewalPreRate() ).as(" transaction.getSubscription().getPricePoint().getRenewalPreRate()" ).isEqualTo(new Double(-1.0)) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().isOverrideDisallowPreRateFlag() ).as(" transaction.getSubscription().getPricePoint().isOverrideDisallowPreRateFlag()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getContentCategory() ).as(" transaction.getSubscription().getPricePoint().getContentCategory()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getPartnerUrl() ).as(" transaction.getSubscription().getPricePoint().getPartnerUrl()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getPartnerContactInfo() ).as(" transaction.getSubscription().getPricePoint().getPartnerContactInfo()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getPartnerEmail() ).as(" transaction.getSubscription().getPricePoint().getPartnerEmail()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getPartnerName() ).as(" transaction.getSubscription().getPricePoint().getPartnerName()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getSubRenewalCounterToLinkedPricepoint() ).as(" transaction.getSubscription().getPricePoint().getSubRenewalCounterToLinkedPricepoint()" ).isEqualTo(-1) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getPPtRenewalCounterToLinkedPricepoint() ).as(" transaction.getSubscription().getPricePoint().getPPtRenewalCounterToLinkedPricepoint()" ).isEqualTo(-1) ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getSubRenewalPricepointId() ).as(" transaction.getSubscription().getPricePoint().getSubRenewalPricepointId()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getLinkPricepointId() ).as(" transaction.getSubscription().getPricePoint().getLinkPricepointId()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getSubPurchaseTransactionTrial() ).as(" transaction.getSubscription().getPricePoint().getSubPurchaseTransactionTrial()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getDiscardHiddenInactivePricepoints() ).as(" transaction.getSubscription().getPricePoint().getDiscardHiddenInactivePricepoints()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().isDiscardMiddleAdvancedPricepoints() ).as(" transaction.getSubscription().getPricePoint().isDiscardMiddleAdvancedPricepoints()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPricePoint().getExtIdentifier1() ).as(" transaction.getSubscription().getPricePoint().getExtIdentifier1()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getExtIdentifier2() ).as(" transaction.getSubscription().getPricePoint().getExtIdentifier2()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getExtIdentifier3() ).as(" transaction.getSubscription().getPricePoint().getExtIdentifier3()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getLanguageLocale() ).as(" transaction.getSubscription().getPricePoint().getLanguageLocale()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getExternalField1() ).as(" transaction.getSubscription().getPricePoint().getExternalField1()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getExternalField2() ).as(" transaction.getSubscription().getPricePoint().getExternalField2()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getExternalTransId() ).as(" transaction.getSubscription().getPricePoint().getExternalTransId()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getAccessChannel() ).as(" transaction.getSubscription().getPricePoint().getAccessChannel()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getPurchaseChannel() ).as(" transaction.getSubscription().getPricePoint().getPurchaseChannel()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getDeviceID() ).as(" transaction.getSubscription().getPricePoint().getDeviceID()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getLocal() ).as(" transaction.getSubscription().getPricePoint().getLocal()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getMsisdn() ).as(" transaction.getSubscription().getPricePoint().getMsisdn()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getLanguageCode() ).as(" transaction.getSubscription().getPricePoint().getLanguageCode()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getActiveSubscriptions() ).as(" transaction.getSubscription().getPricePoint().getActiveSubscriptions()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPricePoint().getCsrId() ).as(" transaction.getSubscription().getPricePoint().getCsrId()" ).isNull();
        softly.assertThat(transaction.getSubscription().isActive() ).as(" transaction.getSubscription().isActive()" ).isTrue() ;
        softly.assertThat(transaction.getSubscription().getPaymentType() ).as(" transaction.getSubscription().getPaymentType()" ).isEqualTo(10010) ;
        softly.assertThat(transaction.getSubscription().getMerchantName() ).as(" transaction.getSubscription().getMerchantName()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRenewalPreRate() ).as(" transaction.getSubscription().getRenewalPreRate()" ).isEqualTo(new Double(-1.0)) ;
        softly.assertThat(transaction.getSubscription().getExtIdentifier1() ).as(" transaction.getSubscription().getExtIdentifier1()" ).isNull();
        softly.assertThat(transaction.getSubscription().getExtIdentifier2() ).as(" transaction.getSubscription().getExtIdentifier2()" ).isNull();
        softly.assertThat(transaction.getSubscription().getExtIdentifier3() ).as(" transaction.getSubscription().getExtIdentifier3()" ).isNull();
        softly.assertThat(transaction.getSubscription().getMsisdn() ).as(" transaction.getSubscription().getMsisdn()" ).isEqualTo("-1104526973");
        softly.assertThat(transaction.getSubscription().getCsrId() ).as(" transaction.getSubscription().getCsrId()" ).isEqualTo("test");
//check size of array!
        softly.assertThat(transaction.getSubscription().getResourceBalances().length ).as(" transaction.getSubscription().getResourceBalances().length" ).isEqualTo(1) ;
// com.vizzavi.ecommerce.business.common.ChargingResource
        softly.assertThat(transaction.getSubscription().getResourceBalances()[0].getResource().getName() ).as(" transaction.getSubscription().getResourceBalances()[0].getResource().getName()" ).isEqualTo("SINGLE_1100035");
        softly.assertThat(transaction.getSubscription().getResourceBalances()[0].getResource().isCurrency() ).as(" transaction.getSubscription().getResourceBalances()[0].getResource().isCurrency()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getResourceBalances()[0].getResource().isResource() ).as(" transaction.getSubscription().getResourceBalances()[0].getResource().isResource()" ).isTrue() ;
        softly.assertThat(transaction.getSubscription().getResourceBalances()[0].getResource().isToken() ).as(" transaction.getSubscription().getResourceBalances()[0].getResource().isToken()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getResourceBalances()[0].getResource().isUsageToken() ).as(" transaction.getSubscription().getResourceBalances()[0].getResource().isUsageToken()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getResourceBalances()[0].getResource().isPayToken() ).as(" transaction.getSubscription().getResourceBalances()[0].getResource().isPayToken()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getResourceBalances()[0].getResource().getResourceSymbol() ).as(" transaction.getSubscription().getResourceBalances()[0].getResource().getResourceSymbol()" ).isEqualTo("ChargingResource_Symbol_1100035");
        softly.assertThat(transaction.getSubscription().getResourceBalances()[0].getResource().getCode() ).as(" transaction.getSubscription().getResourceBalances()[0].getResource().getCode()" ).isEqualTo(1100035) ;
        softly.assertThat(transaction.getSubscription().getResourceBalances()[0].getResource().getDescription() ).as(" transaction.getSubscription().getResourceBalances()[0].getResource().getDescription()" ).isEqualTo("MULTIPLE_1100035");
        softly.assertThat(transaction.getSubscription().getResourceBalances()[0].getResource().getResourceName() ).as(" transaction.getSubscription().getResourceBalances()[0].getResource().getResourceName()" ).isEqualTo("ChargingResource_1100035");
        softly.assertThat(transaction.getSubscription().getResourceBalances()[0].getResource().getCountryId() ).as(" transaction.getSubscription().getResourceBalances()[0].getResource().getCountryId()" ).isEqualTo(0) ;
        softly.assertThat(transaction.getSubscription().getResourceBalances()[0].getSubscriptionIdLong() ).as(" transaction.getSubscription().getResourceBalances()[0].getSubscriptionIdLong()" ).isEqualTo(new Long(8542)) ;
        softly.assertThat(transaction.getSubscription().getResourceBalances()[0].getBalance() ).as(" transaction.getSubscription().getResourceBalances()[0].getBalance()" ).isEqualTo(new Double(1.0)) ;
        softly.assertThat(transaction.getSubscription().getResourceBalances()[0].getPackageId() ).as(" transaction.getSubscription().getResourceBalances()[0].getPackageId()" ).isNull();
        softly.assertThat(transaction.getSubscription().getResourceBalances()[0].getSubscriptionId() ).as(" transaction.getSubscription().getResourceBalances()[0].getSubscriptionId()" ).isEqualTo("8542");
        softly.assertThat(transaction.getSubscription().getResourceBalances()[0].getOldestSubscriptionId() ).as(" transaction.getSubscription().getResourceBalances()[0].getOldestSubscriptionId()" ).isNull();
        softly.assertThat(transaction.getSubscription().getResourceBalances()[0].getSubscription() ).as(" transaction.getSubscription().getResourceBalances()[0].getSubscription()" ).isNull();
        softly.assertThat(transaction.getSubscription().getResourceBalances()[0].getThreshold() ).as(" transaction.getSubscription().getResourceBalances()[0].getThreshold()" ).isEqualTo(0) ;
        softly.assertThat(transaction.getSubscription().getPackageId() ).as(" transaction.getSubscription().getPackageId()" ).isNull();
        softly.assertThat(transaction.getSubscription().isArchived() ).as(" transaction.getSubscription().isArchived()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getExtensionPeriod() ).as(" transaction.getSubscription().getExtensionPeriod()" ).isEqualTo(0) ;
        softly.assertThat(transaction.getSubscription().isRecurring() ).as(" transaction.getSubscription().isRecurring()" ).isTrue() ;
        softly.assertThat(transaction.getSubscription().getSubscriptionId() ).as(" transaction.getSubscription().getSubscriptionId()" ).isEqualTo("8542");
        softly.assertThat(transaction.getSubscription().getOptions() ).as(" transaction.getSubscription().getOptions()" ).isNull();
        softly.assertThat(transaction.getSubscription().isRefundable() ).as(" transaction.getSubscription().isRefundable()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().isSuperPackage() ).as(" transaction.getSubscription().isSuperPackage()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPackageClass() ).as(" transaction.getSubscription().getPackageClass()" ).isNull();
        softly.assertThat(transaction.getSubscription().getAccount() ).as(" transaction.getSubscription().getAccount()" ).isNull();
        softly.assertThat(transaction.getSubscription().isInactiveOrClosed() ).as(" transaction.getSubscription().isInactiveOrClosed()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().isFailed() ).as(" transaction.getSubscription().isFailed()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().isBeingProvisioned() ).as(" transaction.getSubscription().isBeingProvisioned()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().isReserved() ).as(" transaction.getSubscription().isReserved()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getLinkedPtID() ).as(" transaction.getSubscription().getLinkedPtID()" ).isNull();
        softly.assertThat(transaction.getSubscription().isPreOrdered() ).as(" transaction.getSubscription().isPreOrdered()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getContentPaymentType() ).as(" transaction.getSubscription().getContentPaymentType()" ).isEqualTo(10010) ;
        softly.assertThat(transaction.getSubscription().getPurchaseDeviceType() ).as(" transaction.getSubscription().getPurchaseDeviceType()" ).isEqualTo(999) ;
        softly.assertThat(transaction.getSubscription().getNextCyclePercentDiscount() ).as(" transaction.getSubscription().getNextCyclePercentDiscount()" ).isEqualTo(new Double(0.0)) ;
        softly.assertThat(transaction.getSubscription().getNextPaymentAmount() ).as(" transaction.getSubscription().getNextPaymentAmount()" ).isEqualTo(new Double(10.0)) ;
//check size of array!
        softly.assertThat(transaction.getSubscription().getServiceIds().length ).as(" transaction.getSubscription().getServiceIds().length" ).isEqualTo(1) ;
// com.vodafone.global.er.subscriptionmanagement.ERRatingAttributes
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getChannel() ).as(" transaction.getSubscription().getRatingAttributes().getChannel()" ).isEqualTo(999) ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getPartnerId() ).as(" transaction.getSubscription().getRatingAttributes().getPartnerId()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getMultiUsageMode() ).as(" transaction.getSubscription().getRatingAttributes().getMultiUsageMode()" ).isEqualTo(0) ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getNetworkCodeMatchMethod() ).as(" transaction.getSubscription().getRatingAttributes().getNetworkCodeMatchMethod()" ).isEqualTo(0) ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().isPreRatePriceGross() ).as(" transaction.getSubscription().getRatingAttributes().isPreRatePriceGross()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getPreRate() ).as(" transaction.getSubscription().getRatingAttributes().getPreRate()" ).isEqualTo(new Double(-1.0)) ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getPaymentInformation() ).as(" transaction.getSubscription().getRatingAttributes().getPaymentInformation()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getContentName() ).as(" transaction.getSubscription().getRatingAttributes().getContentName()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getAssetID() ).as(" transaction.getSubscription().getRatingAttributes().getAssetID()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getPremiumLevel() ).as(" transaction.getSubscription().getRatingAttributes().getPremiumLevel()" ).isEqualTo(999) ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getReserveOnlyFlag() ).as(" transaction.getSubscription().getRatingAttributes().getReserveOnlyFlag()" ).isEqualTo(0) ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getSupplierId() ).as(" transaction.getSubscription().getRatingAttributes().getSupplierId()" ).isEqualTo("*");
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getDeviceType() ).as(" transaction.getSubscription().getRatingAttributes().getDeviceType()" ).isEqualTo(999) ;
//check size of array!
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getUserGroups().length ).as(" transaction.getSubscription().getRatingAttributes().getUserGroups().length" ).isEqualTo(1) ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getUserGroup() ).as(" transaction.getSubscription().getRatingAttributes().getUserGroup()" ).isEqualTo("*");
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getPaymentType() ).as(" transaction.getSubscription().getRatingAttributes().getPaymentType()" ).isEqualTo(10010) ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getEventDateTime() ).as(" transaction.getSubscription().getRatingAttributes().getEventDateTime()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getEventUnits() ).as(" transaction.getSubscription().getRatingAttributes().getEventUnits()" ).isEqualTo(new Double(0.0)) ;
//check size of array!
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getPromoCodes().length ).as(" transaction.getSubscription().getRatingAttributes().getPromoCodes().length" ).isEqualTo(1) ;
//check size of array!
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getBearerIds().length ).as(" transaction.getSubscription().getRatingAttributes().getBearerIds().length" ).isEqualTo(1) ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getPromoCode() ).as(" transaction.getSubscription().getRatingAttributes().getPromoCode()" ).isEqualTo("*");
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getDuration() ).as(" transaction.getSubscription().getRatingAttributes().getDuration()" ).isEqualTo(2) ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getChargingMethod() ).as(" transaction.getSubscription().getRatingAttributes().getChargingMethod()" ).isEqualTo(3) ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getBearer() ).as(" transaction.getSubscription().getRatingAttributes().getBearer()" ).isEqualTo("*");
        softly.assertThat(transaction.getSubscription().getRatingAttributes().isInteractive() ).as(" transaction.getSubscription().getRatingAttributes().isInteractive()" ).isTrue() ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().isIncludeUnavailable() ).as(" transaction.getSubscription().getRatingAttributes().isIncludeUnavailable()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getExpressFlag() ).as(" transaction.getSubscription().getRatingAttributes().getExpressFlag()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().isExpressFlag() ).as(" transaction.getSubscription().getRatingAttributes().isExpressFlag()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().isPreOrder() ).as(" transaction.getSubscription().getRatingAttributes().isPreOrder()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().isCancellationUsage() ).as(" transaction.getSubscription().getRatingAttributes().isCancellationUsage()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getTierName() ).as(" transaction.getSubscription().getRatingAttributes().getTierName()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getPromoPrecode() ).as(" transaction.getSubscription().getRatingAttributes().getPromoPrecode()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getUniquePromoCode() ).as(" transaction.getSubscription().getRatingAttributes().getUniquePromoCode()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getPromoUniqueCode() ).as(" transaction.getSubscription().getRatingAttributes().getPromoUniqueCode()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getNextCycleDiscount() ).as(" transaction.getSubscription().getRatingAttributes().getNextCycleDiscount()" ).isEqualTo(new Double(0.0)) ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getHasHistoricPricePointFlag() ).as(" transaction.getSubscription().getRatingAttributes().getHasHistoricPricePointFlag()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().isIsForRenewal() ).as(" transaction.getSubscription().getRatingAttributes().isIsForRenewal()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getTaxRate() ).as(" transaction.getSubscription().getRatingAttributes().getTaxRate()" ).isEqualTo(new Double(-1.0)) ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getTaxRateAsDouble() ).as(" transaction.getSubscription().getRatingAttributes().getTaxRateAsDouble()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getAffiliateID() ).as(" transaction.getSubscription().getRatingAttributes().getAffiliateID()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getTariff() ).as(" transaction.getSubscription().getRatingAttributes().getTariff()" ).isEqualTo("*");
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getAggregatorId() ).as(" transaction.getSubscription().getRatingAttributes().getAggregatorId()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().isForcePurchaseFlow() ).as(" transaction.getSubscription().getRatingAttributes().isForcePurchaseFlow()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getReceipientMsisdn() ).as(" transaction.getSubscription().getRatingAttributes().getReceipientMsisdn()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getProductCode() ).as(" transaction.getSubscription().getRatingAttributes().getProductCode()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getMerchantName() ).as(" transaction.getSubscription().getRatingAttributes().getMerchantName()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getInvoiceText() ).as(" transaction.getSubscription().getRatingAttributes().getInvoiceText()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().isReIssueEnabled() ).as(" transaction.getSubscription().getRatingAttributes().isReIssueEnabled()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().isReIssueFlagPresent() ).as(" transaction.getSubscription().getRatingAttributes().isReIssueFlagPresent()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getShortPackageId() ).as(" transaction.getSubscription().getRatingAttributes().getShortPackageId()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getTaxCode() ).as(" transaction.getSubscription().getRatingAttributes().getTaxCode()" ).isEqualTo("*");
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getHistoryStartDate() ).as(" transaction.getSubscription().getRatingAttributes().getHistoryStartDate()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getVendorId() ).as(" transaction.getSubscription().getRatingAttributes().getVendorId()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().isIsForNextPaymentAmount() ).as(" transaction.getSubscription().getRatingAttributes().isIsForNextPaymentAmount()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getRenewalPreRate() ).as(" transaction.getSubscription().getRatingAttributes().getRenewalPreRate()" ).isEqualTo(new Double(-1.0)) ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().isOverrideDisallowPreRateFlag() ).as(" transaction.getSubscription().getRatingAttributes().isOverrideDisallowPreRateFlag()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getContentCategory() ).as(" transaction.getSubscription().getRatingAttributes().getContentCategory()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getPartnerUrl() ).as(" transaction.getSubscription().getRatingAttributes().getPartnerUrl()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getPartnerContactInfo() ).as(" transaction.getSubscription().getRatingAttributes().getPartnerContactInfo()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getPartnerEmail() ).as(" transaction.getSubscription().getRatingAttributes().getPartnerEmail()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getPartnerName() ).as(" transaction.getSubscription().getRatingAttributes().getPartnerName()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getSubRenewalCounterToLinkedPricepoint() ).as(" transaction.getSubscription().getRatingAttributes().getSubRenewalCounterToLinkedPricepoint()" ).isEqualTo(-1) ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getPPtRenewalCounterToLinkedPricepoint() ).as(" transaction.getSubscription().getRatingAttributes().getPPtRenewalCounterToLinkedPricepoint()" ).isEqualTo(-1) ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getLinkedByTrialPricepoint() ).as(" transaction.getSubscription().getRatingAttributes().getLinkedByTrialPricepoint()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getSubRenewalPricepointId() ).as(" transaction.getSubscription().getRatingAttributes().getSubRenewalPricepointId()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getLinkPricepointId() ).as(" transaction.getSubscription().getRatingAttributes().getLinkPricepointId()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getSubPurchaseTransactionTrial() ).as(" transaction.getSubscription().getRatingAttributes().getSubPurchaseTransactionTrial()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getDiscardHiddenInactivePricepoints() ).as(" transaction.getSubscription().getRatingAttributes().getDiscardHiddenInactivePricepoints()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().isDiscardMiddleAdvancedPricepoints() ).as(" transaction.getSubscription().getRatingAttributes().isDiscardMiddleAdvancedPricepoints()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getExtIdentifier1() ).as(" transaction.getSubscription().getRatingAttributes().getExtIdentifier1()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getExtIdentifier2() ).as(" transaction.getSubscription().getRatingAttributes().getExtIdentifier2()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getExtIdentifier3() ).as(" transaction.getSubscription().getRatingAttributes().getExtIdentifier3()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getLanguageLocale() ).as(" transaction.getSubscription().getRatingAttributes().getLanguageLocale()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getExternalField1() ).as(" transaction.getSubscription().getRatingAttributes().getExternalField1()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getExternalField2() ).as(" transaction.getSubscription().getRatingAttributes().getExternalField2()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getExternalTransId() ).as(" transaction.getSubscription().getRatingAttributes().getExternalTransId()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getAccessChannel() ).as(" transaction.getSubscription().getRatingAttributes().getAccessChannel()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getPurchaseChannel() ).as(" transaction.getSubscription().getRatingAttributes().getPurchaseChannel()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getDeviceID() ).as(" transaction.getSubscription().getRatingAttributes().getDeviceID()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getLocal() ).as(" transaction.getSubscription().getRatingAttributes().getLocal()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getMsisdn() ).as(" transaction.getSubscription().getRatingAttributes().getMsisdn()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getLanguageCode() ).as(" transaction.getSubscription().getRatingAttributes().getLanguageCode()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getActiveSubscriptions() ).as(" transaction.getSubscription().getRatingAttributes().getActiveSubscriptions()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRatingAttributes().getCsrId() ).as(" transaction.getSubscription().getRatingAttributes().getCsrId()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPaymentTransactionId() ).as(" transaction.getSubscription().getPaymentTransactionId()" ).isEqualTo(new Long(9216)) ;
        softly.assertThat(transaction.getSubscription().getNonRefundDescription() ).as(" transaction.getSubscription().getNonRefundDescription()" ).isNull();
        softly.assertThat(transaction.getSubscription().getInteractiveUsageFlag() ).as(" transaction.getSubscription().getInteractiveUsageFlag()" ).isEqualTo(2) ;
        softly.assertThat(transaction.getSubscription().isFirstUsage() ).as(" transaction.getSubscription().isFirstUsage()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().isSubscriptionUsed() ).as(" transaction.getSubscription().isSubscriptionUsed()" ).isTrue() ;
        softly.assertThat(transaction.getSubscription().getCurrentNoOfOccurences() ).as(" transaction.getSubscription().getCurrentNoOfOccurences()" ).isEqualTo(new Long(-1)) ;
        softly.assertThat(transaction.getSubscription().getPenaltyCharge() ).as(" transaction.getSubscription().getPenaltyCharge()" ).isEqualTo(new Double(0.0)) ;
        softly.assertThat(transaction.getSubscription().isMinSubscriptionPeriodElapsed() ).as(" transaction.getSubscription().isMinSubscriptionPeriodElapsed()" ).isTrue() ;
        softly.assertThat(transaction.getSubscription().isUnderGracePeriod() ).as(" transaction.getSubscription().isUnderGracePeriod()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getBatchRetryDate() ).as(" transaction.getSubscription().getBatchRetryDate()" ).isNull();
        softly.assertThat(transaction.getSubscription().getOverdueExpiryDate() ).as(" transaction.getSubscription().getOverdueExpiryDate()" ).isNull();
        softly.assertThat(transaction.getSubscription().getLastExpiryDate() ).as(" transaction.getSubscription().getLastExpiryDate()" ).isNull();
        softly.assertThat(transaction.getSubscription().isWasRecurringTrial() ).as(" transaction.getSubscription().isWasRecurringTrial()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getParentPackageID() ).as(" transaction.getSubscription().getParentPackageID()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPreviousStatus() ).as(" transaction.getSubscription().getPreviousStatus()" ).isEqualTo(0) ;
        softly.assertThat(transaction.getSubscription().isParentAlsoPurchased() ).as(" transaction.getSubscription().isParentAlsoPurchased()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().isProvisionOnUsageSuccess() ).as(" transaction.getSubscription().isProvisionOnUsageSuccess()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getLastUsageTransactionIdForSameContent() ).as(" transaction.getSubscription().getLastUsageTransactionIdForSameContent()" ).isEqualTo(new Long(-1)) ;
        softly.assertThat(transaction.getSubscription().getSpId() ).as(" transaction.getSubscription().getSpId()" ).isNull();
        softly.assertThat(transaction.getSubscription().getPartnerTaxRate() ).as(" transaction.getSubscription().getPartnerTaxRate()" ).isEqualTo(new Double(-1.0)) ;
        softly.assertThat(transaction.getSubscription().getCountryId() ).as(" transaction.getSubscription().getCountryId()" ).isNull();
        softly.assertThat(transaction.getSubscription().isWasRecurringPromoCode() ).as(" transaction.getSubscription().isWasRecurringPromoCode()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getLastPaymentTransaction() ).as(" transaction.getSubscription().getLastPaymentTransaction()" ).isNull();
        softly.assertThat(transaction.getSubscription().getB2BPartner() ).as(" transaction.getSubscription().getB2BPartner()" ).isNull();
        softly.assertThat(transaction.getSubscription().getRenewalCounterToLinkedPricepoint() ).as(" transaction.getSubscription().getRenewalCounterToLinkedPricepoint()" ).isEqualTo(-1) ;
        softly.assertThat(transaction.getSubscription().isRenewalPreRateGross() ).as(" transaction.getSubscription().isRenewalPreRateGross()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getNextPricePointId() ).as(" transaction.getSubscription().getNextPricePointId()" ).isNull();
        softly.assertThat(transaction.getSubscription().getLastPaymentTransactionAmount() ).as(" transaction.getSubscription().getLastPaymentTransactionAmount()" ).isEqualTo(new Double(11.75)) ;
        softly.assertThat(transaction.getSubscription().getLastToLastPaymentTransactionAmount() ).as(" transaction.getSubscription().getLastToLastPaymentTransactionAmount()" ).isEqualTo(new Double(-1.0)) ;
        softly.assertThat(transaction.getSubscription().isPricePointChangeOnRenewal() ).as(" transaction.getSubscription().isPricePointChangeOnRenewal()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getOldSubscriptionId() ).as(" transaction.getSubscription().getOldSubscriptionId()" ).isEqualTo(new Long(-1)) ;
        softly.assertThat(transaction.getSubscription().getOldMsisdn() ).as(" transaction.getSubscription().getOldMsisdn()" ).isNull();
        softly.assertThat(transaction.getSubscription().isProvisionable() ).as(" transaction.getSubscription().isProvisionable()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getFuturePricePointRenewals() ).as(" transaction.getSubscription().getFuturePricePointRenewals()" ).isEqualTo(-1) ;
        softly.assertThat(transaction.getSubscription().getNextCyclePercentValue() ).as(" transaction.getSubscription().getNextCyclePercentValue()" ).isEqualTo(new Double(0.0)) ;
        softly.assertThat(transaction.getSubscription().getLockId() ).as(" transaction.getSubscription().getLockId()" ).isEqualTo(new Long(1)) ;
        softly.assertThat(transaction.getSubscription().isSuspended() ).as(" transaction.getSubscription().isSuspended()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().isDefault() ).as(" transaction.getSubscription().isDefault()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().isPromotional() ).as(" transaction.getSubscription().isPromotional()" ).isFalse() ;
        softly.assertThat(transaction.getSubscription().getPromotionalExpiryDate() ).as(" transaction.getSubscription().getPromotionalExpiryDate()" ).isNull();
        softly.assertThat(transaction.getSubscription().getStatus() ).as(" transaction.getSubscription().getStatus()" ).isEqualTo(1) ;
        softly.assertThat(transaction.getSubscription().getExternalSubId() ).as(" transaction.getSubscription().getExternalSubId()" ).isNull();
        softly.assertThat(transaction.getSubscription().getMicroServiceSubList() ).as(" transaction.getSubscription().getMicroServiceSubList()" ).isNull();
        softly.assertThat(transaction.getDescription() ).as(" transaction.getDescription()" ).isNull();
        softly.assertThat(transaction.getNonRefundableDescription() ).as(" transaction.getNonRefundableDescription()" ).isNullOrEmpty();
        softly.assertThat(transaction.isRefundable() ).as(" transaction.isRefundable()" ).isTrue() ;
// com.vizzavi.ecommerce.business.common.ChargingResource
        softly.assertThat(transaction.getChargingResource().getName() ).as(" transaction.getChargingResource().getName()" ).isEqualTo("GBP");
        softly.assertThat(transaction.getChargingResource().isCurrency() ).as(" transaction.getChargingResource().isCurrency()" ).isTrue() ;
        softly.assertThat(transaction.getChargingResource().isResource() ).as(" transaction.getChargingResource().isResource()" ).isFalse() ;
        softly.assertThat(transaction.getChargingResource().isToken() ).as(" transaction.getChargingResource().isToken()" ).isFalse() ;
        softly.assertThat(transaction.getChargingResource().isUsageToken() ).as(" transaction.getChargingResource().isUsageToken()" ).isFalse() ;
        softly.assertThat(transaction.getChargingResource().isPayToken() ).as(" transaction.getChargingResource().isPayToken()" ).isFalse() ;
        softly.assertThat(transaction.getChargingResource().getResourceSymbol() ).as(" transaction.getChargingResource().getResourceSymbol()" ).isEqualTo("ChargingResource_Symbol_826");
        softly.assertThat(transaction.getChargingResource().getCode() ).as(" transaction.getChargingResource().getCode()" ).isEqualTo(826) ;
        softly.assertThat(transaction.getChargingResource().getDescription() ).as(" transaction.getChargingResource().getDescription()" ).isNull();
        softly.assertThat(transaction.getChargingResource().getResourceName() ).as(" transaction.getChargingResource().getResourceName()" ).isEqualTo("ChargingResource_826");
        softly.assertThat(transaction.getChargingResource().getCountryId() ).as(" transaction.getChargingResource().getCountryId()" ).isEqualTo(0) ;
        softly.assertThat(transaction.getStandardRate() ).as(" transaction.getStandardRate()" ).isEqualTo(new Double(11.75)) ;
        softly.assertThat(transaction.getSpId() ).as(" transaction.getSpId()" ).isNull();
        softly.assertThat(transaction.getParentTransactionIdLong() ).as(" transaction.getParentTransactionIdLong()" ).isEqualTo(new Long(0)) ;
        softly.assertThat(transaction.getReIssue() ).as(" transaction.getReIssue()" ).isEqualTo(0) ;
        softly.assertThat(transaction.getLocalPurchaseDate() ).as(" transaction.getLocalPurchaseDate()" ).isNull();
        softly.assertThat(transaction.getLocalPurchaseDateCal() ).as(" transaction.getLocalPurchaseDateCal()" ).isNull();
        softly.assertThat(transaction.getPurchaseRate() ).as(" transaction.getPurchaseRate()" ).isEqualTo(new Double(11.75)) ;
        softly.assertThat(transaction.getPurchaseNetRate() ).as(" transaction.getPurchaseNetRate()" ).isEqualTo(new Double(10.0)) ;
// com.vizzavi.ecommerce.business.common.ChargingResource
        softly.assertThat(transaction.getPurchaseCurrency().getName() ).as(" transaction.getPurchaseCurrency().getName()" ).isEqualTo("GBP");
        softly.assertThat(transaction.getPurchaseCurrency().isCurrency() ).as(" transaction.getPurchaseCurrency().isCurrency()" ).isTrue() ;
        softly.assertThat(transaction.getPurchaseCurrency().isResource() ).as(" transaction.getPurchaseCurrency().isResource()" ).isFalse() ;
        softly.assertThat(transaction.getPurchaseCurrency().isToken() ).as(" transaction.getPurchaseCurrency().isToken()" ).isFalse() ;
        softly.assertThat(transaction.getPurchaseCurrency().isUsageToken() ).as(" transaction.getPurchaseCurrency().isUsageToken()" ).isFalse() ;
        softly.assertThat(transaction.getPurchaseCurrency().isPayToken() ).as(" transaction.getPurchaseCurrency().isPayToken()" ).isFalse() ;
        softly.assertThat(transaction.getPurchaseCurrency().getResourceSymbol() ).as(" transaction.getPurchaseCurrency().getResourceSymbol()" ).isEqualTo("ChargingResource_Symbol_826");
        softly.assertThat(transaction.getPurchaseCurrency().getCode() ).as(" transaction.getPurchaseCurrency().getCode()" ).isEqualTo(826) ;
        softly.assertThat(transaction.getPurchaseCurrency().getDescription() ).as(" transaction.getPurchaseCurrency().getDescription()" ).isNull();
        softly.assertThat(transaction.getPurchaseCurrency().getResourceName() ).as(" transaction.getPurchaseCurrency().getResourceName()" ).isEqualTo("ChargingResource_826");
        softly.assertThat(transaction.getPurchaseCurrency().getCountryId() ).as(" transaction.getPurchaseCurrency().getCountryId()" ).isEqualTo(0) ;
        softly.assertThat(transaction.getNextCycleDiscountPercent() ).as(" transaction.getNextCycleDiscountPercent()" ).isEqualTo(new Double(0.0)) ;
        softly.assertThat(transaction.getRefundEnlargementDate() ).as(" transaction.getRefundEnlargementDate()" ).isNull();
        softly.assertThat(transaction.getRefundPaymentTransactionId() ).as(" transaction.getRefundPaymentTransactionId()" ).isNull();
        softly.assertThat(transaction.getRefundPaymentTransactionIdLong() ).as(" transaction.getRefundPaymentTransactionIdLong()" ).isEqualTo(new Long(-1)) ;
        softly.assertThat(transaction.getRefundable() ).as(" transaction.getRefundable()" ).isTrue() ;
        softly.assertThat(transaction.getModificationInfo() ).as(" transaction.getModificationInfo()" ).isNull();
        softly.assertThat(transaction.getClientId() ).as(" transaction.getClientId()" ).isEqualTo("test");
        softly.assertThat(transaction.getHostId() ).as(" transaction.getHostId()" ).isEqualTo("Ravis-MBP.home");
        softly.assertThat(transaction.getNextCycleDiscountValue() ).as(" transaction.getNextCycleDiscountValue()" ).isEqualTo(new Double(0.0)) ;
        softly.assertThat(transaction.getContentDescription() ).as(" transaction.getContentDescription()" ).isNull();
        softly.assertThat(transaction.getAssetId() ).as(" transaction.getAssetId()" ).isNull();
        softly.assertThat(transaction.getBalanceImpact() ).as(" transaction.getBalanceImpact()" ).isEqualTo(0) ;
        softly.assertThat(transaction.getSubRecords() ).as(" transaction.getSubRecords()" ).isNull();
        softly.assertThat(transaction.getDeviceId() ).as(" transaction.getDeviceId()" ).isNull();
        softly.assertThat(transaction.getSuitabilityDecision() ).as(" transaction.getSuitabilityDecision()" ).isEqualTo(0) ;
        softly.assertThat(transaction.isContainsReIssueService() ).as(" transaction.isContainsReIssueService()" ).isFalse() ;
        softly.assertThat(transaction.getIsPrepay() ).as(" transaction.getIsPrepay()" ).isNull();
        softly.assertThat(transaction.getModifyTransactionId() ).as(" transaction.getModifyTransactionId()" ).isNull();
        softly.assertThat(transaction.getChildSpId() ).as(" transaction.getChildSpId()" ).isNull();
        softly.assertThat(transaction.getSpType() ).as(" transaction.getSpType()" ).isNull();
        softly.assertThat(transaction.isRefundTransaction() ).as(" transaction.isRefundTransaction()" ).isFalse() ;
// com.vizzavi.ecommerce.business.selfcare.Transaction$MetaType
        softly.assertThat(transaction.isSuccess() ).as(" transaction.isSuccess()" ).isTrue() ;
        softly.assertThat(transaction.getTransactionIdLong() ).as(" transaction.getTransactionIdLong()" ).isEqualTo(new Long(9216)) ;
        softly.assertThat(transaction.getStatus() ).as(" transaction.getStatus()" ).isEqualTo(101) ;
        softly.assertThat(transaction.getServiceId() ).as(" transaction.getServiceId()" ).isNull();
        softly.assertThat(transaction.getPaymentErrorId() ).as(" transaction.getPaymentErrorId()" ).isEqualTo("OK");
        softly.assertThat(transaction.getPaymentErrorDescription() ).as(" transaction.getPaymentErrorDescription()" ).isNull();
        softly.assertThat(transaction.getTransactionId() ).as(" transaction.getTransactionId()" ).isEqualTo("9216");
        softly.assertThat(transaction.getPaymentStatus() ).as(" transaction.getPaymentStatus()" ).isEqualTo(101) ;
        softly.assertThat(transaction.getTaxAmount() ).as(" transaction.getTaxAmount()" ).isEqualTo(new Double(1.75)) ;
        softly.assertThat(transaction.getPaymentInfo() ).as(" transaction.getPaymentInfo()" ).isEqualTo("This is payment info from Pay Auth handler");
        softly.assertThat(transaction.getSessionId() ).as(" transaction.getSessionId()" ).isNull();
        softly.assertThat(transaction.getReason() ).as(" transaction.getReason()" ).isNull();


        softly.assertAll();

    }
}
